import Head from "next/head";
import { useContext } from "react";
import Feed from "../components/Feed";
import { UserContext } from "../contexts/UserContext";

import { PostsContext } from "../contexts/PostsContext";

export default function Home({ initialPosts }) {
  const [user, setUser] = useContext(UserContext);
  const [posts, setPosts] = useContext(PostsContext);

  return (
    <div className="min-h-[calc(100vh-4rem)] w-full bg-[#f7f7f7]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Feed posts={posts} user={user} />
    </div>
  );
}
